version: '3.6'
services:
  valuter:
      image: archwaynetwork/valuter:latest
      container_name: valuter
      build:
        context: ./
        target: development  # development | test | production (default) # docker-compose up --build
      ports: 
        - 8081:8080
        - 2346:2345
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
      volumes:
        - ./:/root/app
        - ./:/go/src/app
      networks:
        - archwaynetwork
      environment:
        # RPC_ADDRESS: ${RPC_ADDRESS:-wss://rpc.cosmos.network:443}
        POSTGRES_DB: ${POSTGRES_DB:-cosmologger}
        POSTGRES_USER: ${POSTGRES_USER:-root}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
        POSTGRES_PORT: ${POSTGRES_PORT:-5432}
        POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      healthcheck:
        test: curl --fail http://localhost/ || exit 1
        interval: 30s
        retries: 10 # Will try for 5 minutes      
      restart: always
      security_opt:
        - "seccomp:unconfined"
    #   entrypoint: "/root/app/app"

  #----------------#

  cosmologger:
    image: archwaynetwork/cosmologger:latest
    container_name: cosmologger
    build:
      context: ./
      # target: development  # development | test | production (default) # docker-compose up --build
    depends_on: 
      - postgres
    ports: 
      - 8080:8080
      - 2345:2345
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      # - ./:/root/app
      - ../cosmologger:/go/src/app  # We need to use nested repo
      - ./cosmologger_conf.json:/app/conf.json
    networks:
      - archwaynetwork
    environment:
      RPC_ADDRESS: ${RPC_ADDRESS:-https://rpc.augusta-1.archway.tech:443}
      GRPC_ADDRESS: ${RPC_ADDRESS:-grpc.augusta-1.archway.tech:443}
      POSTGRES_DB: ${POSTGRES_DB:-cosmologger}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 30s
      retries: 10 # Will try for 5 minutes      
    restart: always
    security_opt:
      - "seccomp:unconfined"
    # entrypoint: "/root/app/app"
    # entrypoint: "sh -c 'go build . && ./cosmologger'"
    # entrypoint: "tail -f /dev/null"

  #----------------#

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cosmologger}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    volumes:
      - ~/cosmologger_db:/var/lib/postgresql/data
      # - ~/gaia_db:/var/lib/postgresql/data
    networks:
      - archwaynetwork
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always

  #----------------#

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - archwaynetwork
    restart: unless-stopped

  #----------------#  

networks:
  archwaynetwork:
    driver: bridge